### PR TITLE
Fixes new product creation

### LINKED ISSUE #6561: New Product Creation broken
Tested in master (2.1.0).   Press the New Product button in a category with products.  

Expected Result: Product Editing screen.

Actual Result: Error message: "Warning: Product ID#0 cannot be modified, it does not exist."

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #6561

### CODE REVIEW

File: admin/product.php [hunk 1]
```diff
@@ -20,9 +20,11 @@
     $type_handler = $product_lookup->getTypeHandler() . '.php';
 }
 
-if ($product_lookup === null || !$product_lookup->exists()) {
-    $messageStack->add_session(sprintf(WARNING_PRODUCT_DOES_NOT_EXIST, (int)($_GET['pID'] ?? 0)), 'warning');
-    zen_redirect(zen_href_link(FILENAME_CATEGORY_PRODUCT_LISTING));
+if ($action !== 'new_product' && $action !== 'new_product_preview' && $action !== 'insert_product') {
```
Comment (proseLA) [inline admin/product.php:23]: from a readability standpoint, i think `in_array` is better than these multiple conditionals.
