### PR TITLE
Fix sidebox override

### LINKED ISSUE #5000: zc158 modules sideboxes: template override not working
ZC158, php 8.1.8
eg. copy/make
includes\modules\sideboxes\responsive_classic\information.php
Do some change like prefix a link with some text: change does not show, default file is still used
.

### PR DESCRIPTION
**Pull request by scottcwilson**
Fixes #5000

### CODE REVIEW

File: includes/modules/column_left.php [hunk 1]
```diff
@@ -25,7 +25,7 @@
 $column_width = (int)BOX_WIDTH_LEFT;
 foreach ($sideboxes as $sidebox) {
     $boxFile = (new SideboxFinder(new FileSystem))->sideboxPath($sidebox, $template_dir, true);
-    if (file_exists($boxFile)) {
+    if ($boxFile !== false && file_exists($boxFile)) {
```
Comment (lat9) [inline includes/modules/column_left.php:28]: The check for `file_exists` is redundant, since the SideboxFinder has already verified that it exists if the return value isn't `(bool)false`.

Ditto for line 28 of the `column_right.php`, below.
