### PR TITLE
Fixes #3805 - also purchased products broken

### LINKED ISSUE #3805: bug in also purchased products.
https://github.com/zencart/zencart/blob/89621e6e8cc96dfdaa202655026737174195f168/includes/modules/also_purchased_products.php#L15

see:
https://www.zen-cart.com/showthread.php?227029-Customers-who-bought-this-product-also-purchased-doesn-t-show-any-products

i have confirmed.  but i do not have the solution at this hour.

### PR DESCRIPTION
**Pull request by scottcwilson**
1.5.7 backport of #3806

### CODE REVIEW

File: includes/classes/db/mysql/define_queries.php [hunk 1]
```diff
@@ -29,6 +29,5 @@
                      AND opb.orders_id = o.orders_id
                      AND p.products_status = 1
                      GROUP BY p.products_id, p.products_image
-                     ORDER BY date_purchased desc, p.products_id
-                     LIMIT %u");
```
Comment (lat9) [inline includes/classes/db/mysql/define_queries.php:33]: Why did the `LIMIT %u` get removed?  It seems that now **_all_** also-purchases products are going to be pulled with this query.

Comment (scottcwilson) [reply includes/classes/db/mysql/define_queries.php:33]: All are pulled and then MAX_DISPLAY_ALSO_PURCHASED are selected from the set.  See `includes/modules/also_purchased_products.php` line 15.

Comment (drbyte) [reply includes/classes/db/mysql/define_queries.php:33]: A better way to describe the change is that the LIMIT has been relocated from the DEFINE SQL to a parameter on the `$db->ExecuteRandomMulti` function call.

Technically the result is the same.
