### PR TITLE
Fixes #1917 - PHPMailer failure in 2.0

### LINKED ISSUE #1917: Running an order with emails on and mail transport = PHP gives blank page in 1.6
PHPMailer not properly referenced in includes/functions/functions_email.php

[19-Dec-2018 06:16:17 America/New_York] PHP Fatal error:  Class 'PHPMailer\PHPMailer\PHPMailer' not found in /Users/scott/Sites/demo_160/includes/functions/functions_email.php on line 194

### PR DESCRIPTION
**Pull request by scottcwilson**
Checkout and other operations requiring email send will crash if send emails = true and transport = PHPMailer.

### CODE REVIEW

File: includes/functions/functions_email.php [hunk 1]
```diff
@@ -191,6 +191,7 @@ function zen_mail($to_name, $to_address, $email_subject, $email_text, $from_emai
       $zco_notifier->notify('NOTIFY_EMAIL_AFTER_EMAIL_FORMAT_DETERMINED');
 
       // now lets build the mail object with the phpmailer class
+      require DIR_APP_LIBRARY . 'PHPMailer/src/PHPMailer.php';
```
Comment (drbyte) [inline includes/functions/functions_email.php]: @zcwilt shouldn't the class autoloader take care of this, so we don't need to do a manual `require` here?

Comment (scottcwilson) [reply includes/functions/functions_email.php]: includes/auto_loaders/config.core.php 241-248 should be updated in any event.

Comment (scottcwilson) [reply includes/functions/functions_email.php]: But I saw other manual requires for classes such as in includes/application_top.php: 
`DIR_APP_LIBRARY . 'aura/autoload/src/Loader.php';`

Comment (scottcwilson) [reply includes/functions/functions_email.php]: I know for a fact that what's in this PR does work, because I had to test it a bunch of times to get it to work.

Comment (drbyte) [reply includes/functions/functions_email.php]: Will merge for now. May update later to make less rigid. (Preferring to allow class autoloaders do their own requires)
