### PR TITLE
Fix PayPal require USD

### LINKED ISSUE #4749: USD currency required if using php 8.0 and paypal to stop warning
**Describe the bug**
[Zen cart form issue](https://www.zen-cart.com/showthread.php?228785-USD-required-if-using-php-8-0-and-paypal-to-stop-warning&p=1388000#post1388000)

I have been doing some testing with php8.0 and found a potential issue.
If you have PayPal enabled there is a hardcoded limit of 10000 USD in the /includes/modules/payment/paypal/tpl_ec_button.php 
line 45... 
```
 // PayPal module cannot be used for purchase > $10,000 USD equiv
  if ($currencies->value($_SESSION['cart']->total, true, 'USD') > 10000) {
    $paypalec_enabled = false;
  }
```
This requires that you have USD set up as a currency.

**Version**
Zen Cart version:  1.5.7d, 1.5.8
PHP version:  8.0.17
Plugins that may be related: PayPal

**To Reproduce**
Steps to reproduce/demonstrate the behaviour:
1. Set up Zen cart with default currency not USD (e.g. GBP) and do not set up USD in the currency table.
2. Log in to Zen cart store (not admin)
3.  Log file will be produced

```
[26-Apr-2022 10:39:47 Europe/London] Request URI: /sales/index.php?main_page=shopping_cart, IP address: 127.0.0.1
#1  currencies->value() called at [/*****/innerlightcrystals/sales/includes/modules/payment/paypal/tpl_ec_button.php:46]
#2  include(/*****/innerlightcrystals/sales/includes/modules/payment/paypal/tpl_ec_button.php) called at [/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/templates/tpl_shopping_cart_default.php:189]
#3  require(/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/templates/tpl_shopping_cart_default.php) called at [/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/common/tpl_main_page.php:248]
#4  require(/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/common/tpl_main_page.php) called at [/*****/innerlightcrystals/sales/index.php:94]
--> PHP Warning: Undefined array key "USD" in /*****/innerlightcrystals/sales/includes/classes/currencies.php on line 108.

[26-Apr-2022 10:39:47 Europe/London] Request URI: /sales/index.php?main_page=shopping_cart, IP address: 127.0.0.1
#1  currencies->value() called at [/*****/innerlightcrystals/sales/includes/modules/payment/paypal/tpl_ec_button.php:46]
#2  include(/*****/innerlightcrystals/sales/includes/modules/payment/paypal/tpl_ec_button.php) called at [/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/templates/tpl_shopping_cart_default.php:189]
#3  require(/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/templates/tpl_shopping_cart_default.php) called at [/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/common/tpl_main_page.php:248]
#4  require(/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/common/tpl_main_page.php) called at [/*****/innerlightcrystals/sales/index.php:94]
--> PHP Warning: Trying to access array offset on value of type null in /*****/innerlightcrystals/sales/includes/classes/currencies.php on line 108.

[26-Apr-2022 10:39:47 Europe/London] Request URI: /sales/index.php?main_page=shopping_cart, IP address: 127.0.0.1
#1  currencies->value() called at [/*****/innerlightcrystals/sales/includes/modules/payment/paypal/tpl_ec_button.php:46]
#2  include(/*****/innerlightcrystals/sales/includes/modules/payment/paypal/tpl_ec_button.php) called at [/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/templates/tpl_shopping_cart_default.php:189]
#3  require(/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/templates/tpl_shopping_cart_default.php) called at [/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/common/tpl_main_page.php:248]
#4  require(/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/common/tpl_main_page.php) called at [/*****/innerlightcrystals/sales/index.php:94]
--> PHP Warning: Undefined array key "USD" in /*****/innerlightcrystals/sales/includes/classes/currencies.php on line 113.

[26-Apr-2022 10:39:47 Europe/London] Request URI: /sales/index.php?main_page=shopping_cart, IP address: 127.0.0.1
#1  currencies->value() called at [/*****/innerlightcrystals/sales/includes/modules/payment/paypal/tpl_ec_button.php:46]
#2  include(/*****/innerlightcrystals/sales/includes/modules/payment/paypal/tpl_ec_button.php) called at [/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/templates/tpl_shopping_cart_default.php:189]
#3  require(/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/templates/tpl_shopping_cart_default.php) called at [/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/common/tpl_main_page.php:248]
#4  require(/*****/innerlightcrystals/sales/includes/templates/responsive_sheffield_blue/common/tpl_main_page.php) called at [/*****/innerlightcrystals/sales/index.php:94]
--> PHP Warning: Trying to access array offset on value of type null in /*****/innerlightcrystals/sales/includes/classes/currencies.php on line 113.
```

**My concerns are**
1) Is it sufficient to turn off the currency side boxes to prevent USD being displayed, as I believe the currency is supplied via the URL even if it is not shown. It is easily guessable and therefore potentially changeable by someone modifying the URL.
2) Should there be some instruction in the documentation to say that you must set up USD as a currency even if you are not using the currency.
3) If the currency is changed to USD the invoice is produced in USD even if I only accept GBP. This could create a tax issue later and a possible discrepancy for the buyer when they try to compare what the invoice says with their PayPal account or other payment method. I would not want to allow receipt of USD amount if they are doing a bank transfer? I also made a payment with Square_webpay and this was the correct GBP despite showing USD on the invoice.

**Possible Actions**
1) Remove the 10000 USD limit from tpl_ec_button.php 
2) Add new fields to allow value and currency to be entered in the PayPal setup
3) Add new flag to force invoice etc to the default currency and change the appropriate module and template files
4)...... any other ideas you want to throw in to the mix

### PR DESCRIPTION
**Pull request by brittainmark**
This would be better written as a function. Having said that, where do I put it so that it can be called by all these routines.

I have checked to see is 'USD' is a valid currency and if not then fetched the conversion value using the functions_exchange_rates. If that fails to find a rate it will create a warning file with $rate not found similar to now. It will still process the transaction as it does now.

I am expecting feedback to please review.

Will fix #4749

### CODE REVIEW

**Comment by lat9** [comment]
Since it's a PayPal-specific function, I'd suggest creating a separate function file (in `/includes/modules/payment/paypal`) named something like `paypal_currency_check.php` and then do a `require_once` of that module in each of the 3 PHP modules that will be using that function.

I've suggested having the function separate from the already-existing `paypal_functions.php` file just to not have all those additional functions loaded if they're not necessary.

**Comment by brittainmark** [comment]
Have reworked as a function. Thanks, @lat9 sometimes the brain just won't work.

In includes/modules/payment/paypal/tpl_ec_button.php I have moved the check to the top as it saves a lot of unnecessary processing if the basket is greater than 10000 USD.

Please review again.

If OK I'll squash the commits.

File: includes/modules/pages/login/header_php.php [hunk 1]
```diff
@@ -145,25 +145,8 @@
...
-            $rate = $quote_function('USD');
-        }
-    }
-    $multiplier = (defined('CURRENCY_UPLIFT_RATIO') && (int)CURRENCY_UPLIFT_RATIO != 0) ? CURRENCY_UPLIFT_RATIO : 0;
-    $amount = ($_SESSION['cart']->total * $rate * $multiplier);
-}
-$ec_button_enabled = ($paypalec_enabled && $_SESSION['cart']->count_contents() > 0 && $_SESSION['cart']->total > 0 && $amount <= 10000);
-
+require_once DIR_FS_CATALOG . DIR_WS_MODULES . 'payment/paypal/paypal_currency_check.php';
+$ec_button_enabled = ($paypalec_enabled && $_SESSION['cart']->count_contents() > 0 && $_SESSION['cart']->total > 0 && paypalUSDCheck($_SESSION['cart']->total));
```
Comment (lat9) [inline includes/modules/pages/login/header_php.php:149]: Since that `paypalUSDCheck` returns a boolean, my preference (non-binding!) would be to check for an exactly-equal-to on the return.

File: includes/modules/payment/paypal/tpl_ec_button.php [hunk 2]
```diff
@@ -7,7 +7,9 @@
  * @version $Id: Scott C Wilson 2022 Feb 02 Modified in v1.5.8-alpha $
  */
 
-$paypalec_enabled = (defined('MODULE_PAYMENT_PAYPALWPP_STATUS') && MODULE_PAYMENT_PAYPALWPP_STATUS == 'True');
+// PayPal module cannot be used for purchase > $10,000 USD equiv
+require_once DIR_FS_CATALOG . DIR_WS_MODULES . 'payment/paypal/paypal_currency_check.php';
+$paypalec_enabled = (defined('MODULE_PAYMENT_PAYPALWPP_STATUS') && MODULE_PAYMENT_PAYPALWPP_STATUS == 'True'  && paypalUSDCheck($_SESSION['cart']->total));
```
Comment (lat9) [inline includes/modules/payment/paypal/tpl_ec_button.php:12]: Same comment as the login page's header_php.php.

File: includes/modules/payment/paypalwpp.php [hunk 3]
```diff
@@ -280,8 +280,8 @@ function update_status() {
       $this->zcLog('update_status', 'Module disabled because purchase price (' . $order->info['total'] . ') exceeds PayPal-imposed maximum limit of 1000000 JPY.');
     }
     // module cannot be used for purchase > $10,000 USD equiv
-    $order_amount = $this->calc_order_amount($order->info['total'], 'USD', false);
-    if ($order_amount > 10000) {
+    require_once DIR_FS_CATALOG . DIR_WS_MODULES . 'payment/paypal/paypal_currency_check.php';
+    if (!paypalUSDCheck($order->info['total'])) {
```
Comment (lat9) [inline includes/modules/payment/paypalwpp.php:284]: For this one, I'd use `=== false` instead of `!`.

**Review by lat9 — COMMENTED** [review]
Just me being persnickety.

File: includes/modules/pages/login/header_php.php (hunk 1 above)
Comment (brittainmark) [reply includes/modules/pages/login/header_php.php]: Yes agreed. It is clearer and easier to see.

File: includes/modules/payment/paypal/tpl_ec_button.php (hunk 2 above)
Comment (brittainmark) [reply includes/modules/payment/paypal/tpl_ec_button.php]: Yes agreed. It is clearer and easier to see.

File: includes/modules/payment/paypalwpp.php (hunk 3 above)
Comment (brittainmark) [reply includes/modules/payment/paypalwpp.php]: Yes agreed. It is clearer and easier to see.

**Comment by brittainmark** [comment]
All changed and squashed added header to new routine

**Comment by lat9** [comment]
@brittainmark, do you use git commands or a program to do that squash?

**Comment by brittainmark** [comment]
@lat9 I use GitHub desktop (for windows). Easy to use, just drag and drop, as long as you have not changed your base.
Don't know git bash well enough to use command line. Which is why when I get it wrong, I usually start again by copying my changed files and starting a new branch (or deleting the old one and recreating).

**Comment by scottcwilson** [comment]
This fix is causing issues on the admin side in PHP 8.1.

```
--> PHP Warning: Undefined array key "currency" in /Users/scott/sites/client/includes/classes/currencies.php on line 108.
--> PHP Warning: Undefined array key "" in /Users/scott/sites/client/includes/classes/currencies.php on line 108.
--> PHP Warning: Trying to access array offset on value of type null in /Users/scott/sites/client/includes/classes/currencies.php on line 108.
[25-Nov-2022 17:25:05 UTC] PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /Users/scott/sites/client/includes/classes/currencies.php:108
--> PHP Fatal error: Uncaught DivisionByZeroError: Division by zero in /Users/scott/sites/client/includes/classes/currencies.php:108
```
