### PR TITLE
Admin orders show unit/total weight

### LINKED ISSUE #6180: Admin order's details | Replace individual product weight with row based total weight
Could admin order's `product` rows `weight` column be calculated as row based total weight?

When one is processing the order and quickly checks the weight from the row, it might wrongly just use the weight of a one item and not add it with the quantity. This might also be problematic when quantity of a product is lower than 1 (eg. 0.7), and especially on heavy item, weight is too high.

### PR DESCRIPTION
**Pull request by lat9**
Fixes #6180

### CODE REVIEW

File: admin/orders.php [hunk 1]
```diff
@@ -847,11 +856,12 @@ function couponpopupWindow(url) {
...
                 <?php
                     if ($show_orders_weights === true) {
-                        $products_weight = $order->products[$i]['products_weight'];
-                        if ($products_weight === null) {
+                        $products_weight_unit = $order->products[$i]['products_weight'];
+                        if ($products_weight_unit === null) {
                             $products_weight = '&mdash;';
                         } else {
-                            $products_weight .= ' ' . ltrim(TEXT_PRODUCT_WEIGHT_UNIT, ' ');
+                            $products_weight_total = rtrim(number_format((float)($products_weight_unit * $order->products[$i]['qty']), 4), '0.');
```
Comment (drbyte) [inline admin/orders.php:863]: As opposed to `round()`, is `number_format()` intentionally used so as to apply American formatting rules? (The absence of 3rd, 4th params applies comma and period as separators).

Comment (lat9) [reply admin/orders.php:863]: `number_format` was chosen so that a value like `20.120` could be trimmed to `20.12` or a value like `20.000` could be trimmed to `20`.  I wasn't aware that formatting rules applied to weights, since that's not dealt with anywhere else in the code when handling weights.

Comment (lat9) [reply admin/orders.php:863]: Never mind, duh.  I'm (currently) using the default parameters like @drbyte indicated in his initial comment.
