### PR TITLE
Correct canonical link for `product_reviews_info` page

### LINKED ISSUE #6879: Incorrect canonical link generated for `product_reviews_info` pages
... as reported in [this](https://www.zen-cart.com/showthread.php?230472-Canonical-points-to-redirect-for-Reviews-pages) Zen Cart forum posting.

`init_canonical.php` is catching the `_info` match in the page's name:
https://github.com/zencart/zencart/blob/8e7560c917f0d6bb2e40a53f514d1fb5ea447b18/includes/init_includes/init_canonical.php#L57-L62

### PR DESCRIPTION
**Pull request by lat9**
Fixes #6879

### CODE REVIEW

File: includes/init_includes/init_canonical.php [hunk 1]
```diff
@@ -30,88 +65,116 @@
...
+     * home page
+     * this translates index.php?main_page=index to just index.php (or whatever zen_href_link is doing)
+     */
+    case ($this_is_home_page):
+        $canonicalLink = preg_replace('/(index.php)(\?)(main_page=)(' . FILENAME_DEFAULT . ')$/', '', zen_href_link(FILENAME_DEFAULT, '', 'NONSSL', false));
+        break;
+    /**
+     * for all/new/special/featured listings:
+     */
+    case (in_array($current_page, array(FILENAME_FEATURED_PRODUCTS, FILENAME_SPECIALS, FILENAME_PRODUCTS_NEW, FILENAME_PRODUCTS_ALL))):
```
Comment (torvista) [inline includes/init_includes/init_canonical.php:154]: change to short array syntax?

Comment (lat9) [reply includes/init_includes/init_canonical.php:154]: ... because I missed it!  Thanks.

**Comment by lat9** [comment]
Bumpting this; ready for merge.
