### PR TITLE
Fix for missing buttons in empty product-type Extras sub-pages

### LINKED ISSUE #5923: Admin, Extras: all pages missing Insert button
php7.4-8.3
ZC2.0.0.

Delete all demo items on any page so there are no records: no Insert button.

### PR DESCRIPTION
**Pull request by simon1066**
Fixes #5923

Admin > Extras > Media Types was fixed in #5924, this PR fixes the remaining sub-menus

`media_manager.php` may need a closer check as it's possible that I may have lost my way, slightly.

### CODE REVIEW

File: admin/record_company.php [hunk 1]
```diff
@@ -158,6 +158,7 @@
 
                     $aInfo_array = array_merge($record_company, $record_company_products->fields);
                     $aInfo = new objectInfo($aInfo_array);
+					$rCompany_parameter = '&mID=' . $aInfo->record_company_id;
```
Comment (drbyte) [inline admin/record_company.php:161]: Indentation is strange here. Best to use spaces, not tabs.

**Comment by simon1066** [comment]
Thank you. Annoyed that I missed the spaces-not-tabs as I was aware of that, I'll resubmit. Better next time.

**Comment by drbyte** [comment]
Thanks!
