### PR TITLE
Sort observers using natural and case-insenstive sort.

### LINKED ISSUE #7281: Storefront observer loading order: not consistant across operating systems
While investigating some observer misbehavour.....
and sticking in an error log at line 39 to output $observers:
https://github.com/zencart/zencart/blob/77d27a29c36ba1296a49f4be69c4cacab54b2fe0/includes/init_includes/init_observers.php#L38-L41

I get inconsistent array ordering and the subsequent unexpected results with different observers trapping the same notifier, at different moments locally/in production.

locally Windows

 (
    [0] => FULL PATH/zc_plugins/GPSR/v1.0.0/catalog/includes/classes/observers/auto.GpsrObserver.php
    [1] => FULL PATH/zc_plugins/StructuredData/v2.0.0/catalog/includes/classes/observers/auto.structured_data.php
    [2] => FULL PATH/zc_plugins/PackageTracker/v0.0.0/catalog/includes/classes/observers/auto.ty_package_tracker.php
    [3] => FULL PATH/zc_plugins/ZenShortCodes/v1.1.0/catalog/includes/classes/observers/auto.zen_shortcodes.php
    [4] => includes/classes/observers/auto.access_blocker.php
    [5] => includes/classes/observers/auto.back_in_stock_notificationsAccount.php
    [6] => includes/classes/observers/auto.back_in_stock_notificationsProductInfo.php
    [7] => includes/classes/observers/auto.downloads_via_aws.php
    [8] => includes/classes/observers/auto.downloads_via_redirect.php
    [9] => includes/classes/observers/auto.downloads_via_streaming.php
    [10] => includes/classes/observers/auto.downloads_via_url.php
    [11] => includes/classes/observers/auto.google_recaptcha_observer.php
    [12] => includes/classes/observers/auto.instant_search_observer.php
    [13] => includes/classes/observers/auto.MotorvistaMisc.php
    [14] => includes/classes/observers/auto.MotorvistaPaymentFilter.php
    [15] => includes/classes/observers/auto.MotorvistaProductInfo.php
    [16] => includes/classes/observers/auto.MotorvistaWholesaleCatalog.php
    [17] => includes/classes/observers/auto.non_captcha_observer.php
    [18] => includes/classes/observers/auto.paypalrestful.php
    [19] => includes/classes/observers/auto.PluginTradePricing.php
    [20] => includes/classes/observers/auto.prioritize_search_match_in_name.php
    [21] => includes/classes/observers/auto.zen_color_box_observer.php
)

Production Linux 5.14.0-503.33.1.el9_5.x86_64

(
    [0] => FULL PATH/zc_plugins/GPSR/v1.0.0/catalog/includes/classes/observers/auto.GpsrObserver.php
    [1] => FULL PATH/zc_plugins/StructuredData/v2.0.0/catalog/includes/classes/observers/auto.structured_data.php
    [2] => FULL PATH/zc_plugins/PackageTracker/v0.0.0/catalog/includes/classes/observers/auto.ty_package_tracker.php
    [3] => FULL PATH/zc_plugins/ZenShortCodes/v1.1.0/catalog/includes/classes/observers/auto.zen_shortcodes.php
    [4] => includes/classes/observers/auto.MotorvistaProductInfo.php
    [5] => includes/classes/observers/auto.back_in_stock_notificationsProductInfo.php
    [6] => includes/classes/observers/auto.zen_color_box_observer.php
    [7] => includes/classes/observers/auto.MotorvistaPaymentFilter.php
    [8] => includes/classes/observers/auto.back_in_stock_notificationsAccount.php
    [9] => includes/classes/observers/auto.prioritize_search_match_in_name.php
    [10] => includes/classes/observers/auto.access_blocker.php
    [11] => includes/classes/observers/auto.instant_search_observer.php
    [12] => includes/classes/observers/auto.paypalrestful.php
    [13] => includes/classes/observers/auto.MotorvistaWholesaleCatalog.php
    [14] => includes/classes/observers/auto.google_recaptcha_observer.php
    [15] => includes/classes/observers/auto.downloads_via_streaming.php
    [16] => includes/classes/observers/auto.MotorvistaMisc.php
    [17] => includes/classes/observers/auto.downloads_via_url.php
    [18] => includes/classes/observers/auto.downloads_via_aws.php
    [19] => includes/classes/observers/auto.PluginTradePricing.php
    [20] => includes/classes/observers/auto.non_captcha_observer.php
    [21] => includes/classes/observers/auto.downloads_via_redirect.php

sort with SORT_STRING or STRING_NATURAL: uppercase first
(
    [0] => FULL PATH/zc_plugins/GPSR/v1.0.0/catalog/includes/classes/observers/auto.GpsrObserver.php
    [1] => FULL PATH/zc_plugins/PackageTracker/v0.0.0/catalog/includes/classes/observers/auto.ty_package_tracker.php
    [2] => FULL PATH/zc_plugins/StructuredData/v2.0.0/catalog/includes/classes/observers/auto.structured_data.php
    [3] => FULL PATH/zc_plugins/ZenShortCodes/v1.1.0/catalog/includes/classes/observers/auto.zen_shortcodes.php
    [4] => includes/classes/observers/auto.MotorvistaMisc.php
    [5] => includes/classes/observers/auto.MotorvistaPaymentFilter.php
    [6] => includes/classes/observers/auto.MotorvistaProductInfo.php
    [7] => includes/classes/observers/auto.MotorvistaWholesaleCatalog.php
    [8] => includes/classes/observers/auto.PluginTradePricing.php
    [9] => includes/classes/observers/auto.access_blocker.php
    [10] => includes/classes/observers/auto.back_in_stock_notificationsAccount.php
    [11] => includes/classes/observers/auto.back_in_stock_notificationsProductInfo.php
    [12] => includes/classes/observers/auto.downloads_via_aws.php
    [13] => includes/classes/observers/auto.downloads_via_redirect.php
    [14] => includes/classes/observers/auto.downloads_via_streaming.php
    [15] => includes/classes/observers/auto.downloads_via_url.php
    [16] => includes/classes/observers/auto.google_recaptcha_observer.php
    [17] => includes/classes/observers/auto.instant_search_observer.php
    [18] => includes/classes/observers/auto.non_captcha_observer.php
    [19] => includes/classes/observers/auto.paypalrestful.php
    [20] => includes/classes/observers/auto.prioritize_search_match_in_name.php
    [21] => includes/classes/observers/auto.zen_color_box_observer.php
)

using natcasesort...perhaps as expected/as I've used for the moment.
(
    [0] => FULL PATH/zc_plugins/GPSR/v1.0.0/catalog/includes/classes/observers/auto.GpsrObserver.php
    [1] => FULL PATH/zc_plugins/PackageTracker/v0.0.0/catalog/includes/classes/observers/auto.ty_package_tracker.php
    [2] => FULL PATH/zc_plugins/StructuredData/v2.0.0/catalog/includes/classes/observers/auto.structured_data.php
    [3] => FULL PATH/zc_plugins/ZenShortCodes/v1.1.0/catalog/includes/classes/observers/auto.zen_shortcodes.php
    [4] => includes/classes/observers/auto.access_blocker.php
    [5] => includes/classes/observers/auto.back_in_stock_notificationsAccount.php
    [6] => includes/classes/observers/auto.back_in_stock_notificationsProductInfo.php
    [7] => includes/classes/observers/auto.downloads_via_aws.php
    [8] => includes/classes/observers/auto.downloads_via_redirect.php
    [9] => includes/classes/observers/auto.downloads_via_streaming.php
    [10] => includes/classes/observers/auto.downloads_via_url.php
    [11] => includes/classes/observers/auto.google_recaptcha_observer.php
    [12] => includes/classes/observers/auto.instant_search_observer.php
    [13] => includes/classes/observers/auto.MotorvistaMisc.php
    [14] => includes/classes/observers/auto.MotorvistaPaymentFilter.php
    [15] => includes/classes/observers/auto.MotorvistaProductInfo.php
    [16] => includes/classes/observers/auto.MotorvistaWholesaleCatalog.php
    [17] => includes/classes/observers/auto.non_captcha_observer.php
    [18] => includes/classes/observers/auto.paypalrestful.php
    [19] => includes/classes/observers/auto.PluginTradePricing.php
    [20] => includes/classes/observers/auto.prioritize_search_match_in_name.php
    [21] => includes/classes/observers/auto.zen_color_box_observer.php

So, a decision about the preferred ordering and some documentation is required.

### PR DESCRIPTION
**Pull request by drbyte**
Fixes #7281

### CODE REVIEW

File: includes/init_includes/init_observers.php [hunk 1]
```diff
@@ -37,6 +37,14 @@
...
 $observers = array_merge($observersPlugins, $observersMain);
 
+// sort by filename so that observers are loaded in a predictable order
+$basenames = array_map('basename', $observers);
+array_multisort(
+    $basenames, SORT_ASC, SORT_NATURAL | SORT_FLAG_CASE,
+    $observers, SORT_ASC, SORT_NATURAL | SORT_FLAG_CASE
+);
+unset($basenames);
+
```
Comment (torvista) [inline includes/init_includes/init_observers.php:47]: ok for me, all observers are listed in a natural sort.

**Review by lat9 — APPROVED** [review]
While this could introduce some inconsistency in the order in which auto-loaded observers are (er) loaded, it's a stabilizing change.
