### PR TITLE
admin server info HTML5 complient

### LINKED ISSUE #5133: Server info is not HTML5 compliant
**Describe the bug**
The following errors are present.

- The font element is obsolete. Use CSS instead.
- Bad character ( after <. Probable cause: Unescaped <. Try escaping it as &lt;.

Additionally, there are many occurrences of these warnings.

- The border attribute is obsolete. Consider specifying img { border: 0; } in CSS instead.
- The name attribute is obsolete. Consider putting an id attribute on the nearest container instead.
- A table row was 1 columns wide, which is less than the column count established by the first row (2).

**Version**
Zen Cart version: 1.5.8
PHP version: 7.4, 8.0, 8.1 & 8.2

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to 'Admin>version' or 'admin>tools>server version'
2. view page source
3. copy page source 
4. paste into https://validator.w3.org/nu/#textarea
5. click validate

**Expected behavior**
There should be no validation errors.

### PR DESCRIPTION
**Pull request by brittainmark**
fix #5133

I have:

- removed border=0 from \ tag
- changed the doctype to html
- cleaned up the output from phpinfo
   - changed \<font>\</font> to \<span>\</span>
   - replaced name= with id= in \<a> tags
   - removed border=0 from \ tags
   - added a colspan for one occurrence of table row missing \<td>element
- Added htmlspecialchars to the output of system variables

I tested against php 7.4, 8.0, 8.1, 8.2

I had to define a lot of variables in the classes for 8.2. I just set them to public, and it worked fine. (not included in this release)

### CODE REVIEW

File: admin/server_info.php [hunk 1]
```diff
@@ -113,7 +116,7 @@
         ?>
         <tr class="db-row">
             <td class="db-info db-name"><?php echo $variable['Variable_name']; ?></td>
-            <td class="db-info db-value"><?php echo empty($variable['Value']) ? '$nbsp;' : $variable['Value']; ?></td>
+            <td class="db-info db-value"><?php echo empty($variable['Value']) ? '$nbsp;' : htmlspecialchars($variable['Value']); ?></td>
```
Comment (scottcwilson) [inline admin/server_info.php:119]: why did you remove the call to `htmlspecialchars`?

**Review by scottcwilson — CHANGES_REQUESTED** [review]

**Comment by brittainmark** [comment]
I didn't I added a call to htmlspecialchars

File: admin/server_info.php (hunk 1 above)
Comment (brittainmark) [reply admin/server_info.php:119]: I didn't I added a call to htmlspecialchars

Comment (scottcwilson) [reply admin/server_info.php:119]: sorry I misread this.
