### PR TITLE
Resolves issues in delete category

### LINKED ISSUE #2839: Delete of category with no linked product displays linked product text
Found today when testing the deletion of a category that had no linked product that there is a warning presented regarding linked product and ensuring that the link(s) are properly modified; however, this doesn't make sense to display if the category doesn't have linked product.

Good to know the process, but this seems like the wrong point at which to discuss it.  Why?
- Always showing this text regardless the status of the contained product will reduce the importance of what the message is conveying.
- Displaying this message when there are no linked product would cause the concerned store owner to break away from the current action of deleting the category to go check if there is in fact a linked product and send them down some unnecessary path using time that could be better spent managing the store.
- Displaying this text for all conditions may also drive the concerned individual to seek out if there is a problem with the code/database when it is simply useful information provided for the wrong condition.

This was initially a part of: https://github.com/zencart/zencart/blame/f89a3b8269c7b513693ab5a0dce4469fd403cff9/admin/category_product_listing.php#L1041 in: https://github.com/zencart/zencart/pull/1604/files which became:  https://github.com/zencart/zencart/blame/v157/admin/category_product_listing.php#L1045

Perhaps a new function should be added to check if a category has linked product? There is already `zen_get_product_is_linked($products_id)` which either could be used within the function or it could have its own code to determine if the category has linked product.  Seems that if this concept is to be included that it not just be some stand alone code but something that could be otherwise used.

### LINKED ISSUE #3762: Delete Category bugs
Investigating #2839 reveals a number of other bugs: 

- message TEXT_DELETE_WARNING_CHILDS used but not defined.
- delete logic checks variables $cInfo->products_count and $cInfo->childs_count which do not exist.
- message TEXT_DELETE_WARNING_PRODUCTS used but not defined. 

PR coming shortly.

### PR DESCRIPTION
**Pull request by scottcwilson**
Incorrect / missing messages during delete category. 

Fixes #3762 
Fixes #2839

### CODE REVIEW

File: admin/category_product_listing.php [hunk 1]
```diff
@@ -870,26 +870,32 @@
...
+            $products_count = zen_products_in_category_count($cInfo->categories_id);
+            $has_linked = false; 
+            $prod_list = $db->Execute("SELECT * FROM " . TABLE_PRODUCTS_TO_CATEGORIES . " WHERE categories_id = " . $cInfo->categories_id); 
+            foreach ($prod_list as $prod) {
+               $other_cat_list = $db->Execute("SELECT * FROM " . TABLE_PRODUCTS_TO_CATEGORIES . " WHERE products_id = " . $prod['products_id'] . " AND  categories_id != " . $prod['categories_id']);
+               if (!$other_cat_list->EOF) {
+                  $has_linked = true; 
+                  break; 
+               }
+            }
```
Comment (drbyte) [inline admin/category_product_listing.php:883]: Isn't there a function which does this foreach loop already?

Comment (scottcwilson) [reply admin/category_product_listing.php:883]: It's for a different category.

Comment (drbyte) [reply admin/category_product_listing.php:883]: I was thinking of something like this, so that the queries are kept within existing functions that are already doing these lookups:
```suggestion
            $childs_count = zen_childs_in_category_count($cInfo->categories_id);
            $products_count = zen_products_in_category_count($cInfo->categories_id);
            $has_linked = false; 
            $prod_list = zen_get_linked_products_for_category($cInfo->categories_id);
            foreach ($prod_list as $prod) {
               if (zen_get_linked_categories_for_product($prod, $cInfo->categories_id)) {
                  $has_linked = true; 
                  break; 
               }
            }
```

Comment (scottcwilson) [reply admin/category_product_listing.php:883]: OK I see.  I misread your earlier comment - I was thinking you were referring to code higher up in the file (which does indeed do a count but for a different category).  I'll get this done shortly.

Comment (scottcwilson) [reply admin/category_product_listing.php:883]: Your code doesn't quite work - second parm to zen_get_linked_categories_for_product() is supposed to be an array.  But the problem is this also uncovers a bug in zen_get_linked_categories_for_product().  I'm going to put both in this update, please split if you wish.

Comment (drbyte) [reply admin/category_product_listing.php]: Good catch. Thanks.
