### PR TITLE
Do Not Include Error Message in Sprintf

### LINKED ISSUE #5339: Error installing ot_gv if mail cannot be sent and contains %
**Describe the bug**
If you try to install gift certificates and the mail process is not working. If the $mail->ErrorInfo contains % then a white screen is produced and the error log below.

**Version**
Zen Cart version: 1.5.8
PHP version: 8.0.24

**To Reproduce**
Steps to reproduce/demonstrate the behavior:
1. Go to Admin>Discounts>not installed
2. Select Gift Certificates
3. Click install
4. If email is not set up and there is a % in the $mail->ErrorInfo will get white screen and error log below.
**Expected behavior**
error message about e-mail and screen displayed correctly.

**Debug/Error Logs**
```
[21-Oct-2022 14:03:22 Europe/London] PHP Fatal error:  Uncaught ArgumentCountError: 6 arguments are required, 4 given in /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_email.php:395
Stack trace:
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_email.php(395): sprintf()
#1 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/modules.php(108): zen_mail()
#2 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/index.php(11): require('...')
#3 {main}
  thrown in /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_email.php on line 395

[21-Oct-2022 14:03:22 Europe/London] Request URI: /Test158/ADMIN/index.php?cmd=modules&set=ordertotal&action=install, IP address: https://innerlightcrystals.co.uk
--> PHP Fatal error: Uncaught ArgumentCountError: 6 arguments are required, 4 given in /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_email.php:395
Stack trace:
#0 /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_email.php(395): sprintf()
#1 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/modules.php(108): zen_mail()
#2 /home/lotus/public_html/innerlightcrystals/Test158/ADMIN/index.php(11): require('...')
#3 {main}
  thrown in /home/lotus/public_html/innerlightcrystals/Test158/includes/functions/functions_email.php on line 395..
```

### PR DESCRIPTION
**Pull request by brittainmark**
fix #5339

### CODE REVIEW

File: includes/functions/functions_email.php [hunk 1]
```diff
@@ -392,7 +392,7 @@ function zen_mail($to_name, $to_address, $email_subject, $email_text, $from_emai
       } catch (Exception $e) {
       }
       if (!$success) {
-        $msg = sprintf(EMAIL_SEND_FAILED . '&nbsp;'. $mail->ErrorInfo, $to_name, $to_email_address, $email_subject);
+        $msg = sprintf(EMAIL_SEND_FAILED . '&nbsp;'. str_replace('%', '%%',$mail->ErrorInfo), $to_name, $to_email_address, $email_subject);
```
Comment (scottcwilson) [inline includes/functions/functions_email.php:395]: Would it be better to refactor `$mail->ErrorInfo` out of the sprintf?

Maybe 

```
$msg = sprintf(EMAIL_SEND_FAILED, $to_name, $to_email_address, $email_subject) .  '&nbsp;'. $mail->ErrorInfo; 
```

Comment (brittainmark) [reply includes/functions/functions_email.php]: To quote Homer Simpson DOH!!!
That's why we have reviews. Much better and more efficient.

**Comment by brittainmark** [comment]
Thanks @scottcwilson  I assume you should mark as resolved, not me.
